siteName: Kabooly
author: David White
url: https://github.com/webdigga/kabooly
poweredBy: Kabooly
email: david@kabooly.com
phoneNumber: "07877304672"
companyNumber: "15653819"
addressLineOne: "23 Carisbrooke House"
addressLineTwo: "Seven Kings Way"
addressLineThree: "Kingston Upon Thames"
city: "London"
postCode: "KT2 5BS"
country: "GB"
