backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
media_folder: "src/_includes/static/img"
public_folder: "/_includes/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Article"
    name: "article"
    folder: "src/articles"
    create: true
    editor:
      preview: false
    fields:
      - {
        label: "Title",
        name: "title",
        widget: "string",
        hint: "*This title will be used in the page's H1 tag, and also it determines the URL*"
      }
      - { 
        label: "SEO Title",
        name: "seoTitle",
        widget: "string",
        hint: "*This title will be used in the title tag for search engines (less than 60 characters)*"
      }
      - {
        label: "Description",
        name: "description",
        widget: "string",
        hint: "*Used in search engines (more than 70 characters and less than 155 characters)*"
      }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "privacy"]
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "privacy"]
      - label: "Hero image"
        name: "heroImage"
        widget: "image"
        choose_url: true
        required: false
        media_library:
          config:
            multiple: false
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Site Name, name: siteName, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Powered by, name: poweredBy, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Type (type of template), name: type, widget: string }
          - { label: Email, name: email, widget: string }
          - { label: Phone number, name: phoneNumber, widget: string }
          - { label: Company number, name: companyNumber, widget: string }
          - { label: Address Line One, name: addressLineOne, widget: string }
          - { label: Address Line Two, name: addressLineTwo, widget: string }
          - { label: Address Line Three, name: addressLineThree, widget: string }
          - { label: City, name: city, widget: string }
          - { label: Post Code, name: postCode, widget: string }
